apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
    spec:
      containers:
        - name: service
          image: iamfet/shoppingassistantservice:14542275320
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            grpc:
              port: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            grpc:
              port: 8080
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi

---

apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
spec:
  type: ClusterIP
  selector:
    app: shoppingassistantservice
  ports:
    - port: 8080
      targetPort: 8080