name: Product Catalog CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/productcatalogservice/**'
      - '.github/workflows/CI_productcatalogue.yaml'

env:
  GO_VERSION: '1.22'
  SERVICE_PATH: './src/productcatalogservice'
  IMAGE_NAME: 'productcatalogservice'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        working-directory: ${{ env.SERVICE_PATH }}
        run: go mod download

      - name: Build application
        working-directory: ${{ env.SERVICE_PATH }}
        run: go build -v -o product-catalog-service

      - name: Run tests with coverage
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          go test -v -coverprofile=coverage.out ./...